import {
  capsuleActorTypeEnum,
  capsuleArtifactEntryTypeEnum,
  capsuleBranchResourceCleanupPolicyEnum,
  capsuleBranchResourceStatusEnum,
  capsuleBranchResourceTypeEnum,
  capsuleBranchPreviewStatusEnum,
  capsuleBranchStatusEnum,
  capsuleLifecycleStatusEnum,
  capsuleOperationStatusEnum,
  capsuleOperationStepStatusEnum,
  capsuleOperationTypeEnum,
  capsuleRouteAliasStatusEnum,
  capsuleRouteExposureEnum,
  capsuleRouteMethodEnum,
  capsuleRouteProviderEnum,
  capsuleRouteProviderStatusEnum,
  capsuleRouteRevisionActionEnum,
  capsuleRouteRevisionStatusEnum,
  CapsuleSnapshotAgentArtifactContentPolicyEnum,
  capsuleSnapshotCaptureResourceStatusEnum,
  capsuleSnapshotDependencyDigestKindEnum,
  capsuleSnapshotDependencyKindEnum,
  capsuleSnapshotGitRemoteTransportEnum,
  capsuleSnapshotModeEnum,
  capsuleSnapshotResourceKindEnum,
  capsuleSnapshotResourceProviderEnum,
  createCapsuleSchema,
} from '@qiln/core/server'
import { users } from './identity'

/**
 * Shared capsule handles keep Web, SSH, and migration composition bound to the
 * same physical identities without importing either application's runtime.
 */
export const capsuleTables = createCapsuleSchema(users.id)

export {
  capsuleActorTypeEnum,
  capsuleArtifactEntryTypeEnum,
  capsuleBranchResourceCleanupPolicyEnum,
  capsuleBranchResourceStatusEnum,
  capsuleBranchResourceTypeEnum,
  capsuleBranchPreviewStatusEnum,
  capsuleBranchStatusEnum,
  capsuleLifecycleStatusEnum,
  capsuleOperationStatusEnum,
  capsuleOperationStepStatusEnum,
  capsuleOperationTypeEnum,
  capsuleRouteAliasStatusEnum,
  capsuleRouteExposureEnum,
  capsuleRouteMethodEnum,
  capsuleRouteProviderEnum,
  capsuleRouteProviderStatusEnum,
  capsuleRouteRevisionActionEnum,
  capsuleRouteRevisionStatusEnum,
  CapsuleSnapshotAgentArtifactContentPolicyEnum,
  capsuleSnapshotCaptureResourceStatusEnum,
  capsuleSnapshotDependencyDigestKindEnum,
  capsuleSnapshotDependencyKindEnum,
  capsuleSnapshotGitRemoteTransportEnum,
  capsuleSnapshotModeEnum,
  capsuleSnapshotResourceKindEnum,
  capsuleSnapshotResourceProviderEnum,
}

export const {
  capsules,
  capsuleBranches,
  capsuleOperations,
  capsuleCreateOperations,
  capsuleForkOperations,
  capsuleBranchRuntimeOperations,
  capsuleOperationSteps,
  capsuleBranchResources,
  capsuleBranchPreviews,
  capsuleSnapshots,
  capsuleArtifactManifests,
  capsuleArtifactManifestRoots,
  capsuleArtifactEntries,
  capsuleSnapshotGitRepositories,
  capsuleSnapshotGitRemotes,
  capsuleSnapshotDependencyReferences,
  capsuleSnapshotResourceReferences,
  capsuleSnapshotCaptureOperations,
  capsuleSnapshotCaptureResources,
  capsuleRouteAliases,
  capsuleRouteHeads,
  capsuleRouteRevisions,
  capsuleRouteOperations,
  capsuleRouteProviderApplications,
} = capsuleTables

export const capsuleSchema = {
  capsuleActorTypeEnum,
  capsuleArtifactEntryTypeEnum,
  capsuleBranchStatusEnum,
  capsuleBranchPreviewStatusEnum,
  capsuleBranchResourceCleanupPolicyEnum,
  capsuleBranchResourceStatusEnum,
  capsuleBranchResourceTypeEnum,
  capsuleLifecycleStatusEnum,
  capsuleOperationStatusEnum,
  capsuleOperationStepStatusEnum,
  capsuleOperationTypeEnum,
  capsuleRouteAliasStatusEnum,
  capsuleRouteExposureEnum,
  capsuleRouteMethodEnum,
  capsuleRouteProviderEnum,
  capsuleRouteProviderStatusEnum,
  capsuleRouteRevisionActionEnum,
  capsuleRouteRevisionStatusEnum,
  CapsuleSnapshotAgentArtifactContentPolicyEnum,
  capsuleSnapshotCaptureResourceStatusEnum,
  capsuleSnapshotDependencyDigestKindEnum,
  capsuleSnapshotDependencyKindEnum,
  capsuleSnapshotGitRemoteTransportEnum,
  capsuleSnapshotModeEnum,
  capsuleSnapshotResourceKindEnum,
  capsuleSnapshotResourceProviderEnum,
  ...capsuleTables,
} as const
