plugins:
  - prettier-plugin-jsdoc

printWidth: 120
tabWidth: 2
useTabs: false
semi: false
singleQuote: true
trailingComma: all
bracketSpacing: true
bracketSameLine: true
arrowParens: avoid
htmlWhitespaceSensitivity: ignore
endOfLine: lf
vueIndentScriptAndStyle: true

jsdocPrintWidth: 80
jsdocCapitalizeDescription: true
jsdocDescriptionWithDot: true
jsdocDescriptionTag: false
jsdocCommentLineStrategy: multiline
jsdocSeparateReturnsFromParam: false
jsdocSeparateTagGroups: false
jsdocVerticalAlignment: false
jsdocKeepUnParseAbleExampleIndent: true
