export const AWS_SPEC = Object.freeze({
  cliVersion: '2.37.9',
  sdkVersion: '3.1146.0',
  defaultName: 'default',
  defaultRegion: 'us-west-2',
  profile: 'qiln',
  processFile: 'aws.js',
  loginTimeoutMs: 15 * 60 * 1_000,
  requestTimeoutMs: 30_000,
  connectionTimeoutMs: 5_000,
  bootstrap: Object.freeze({
    processFile: 'bootstrap.js',
    record: 'bootstrap.json',
    requestTimeoutMs: 120_000,
    maximumPages: 20,
  }),
  state: {
    directory: 'aws',
    connections: 'connections',
    lock: 'connections.lock',
    connection: 'connection.json',
    operation: 'operation.json',
    auth: 'auth',
    bootstrap: 'bootstrap',
    config: 'config',
    credentials: 'credentials',
    cache: 'cache',
  },
  limits: {
    record: 65_536,
    config: 65_536,
    cache: 262_144,
  },
})
